title:  "Business English in Bocholt"
description: "Mary O'Keeffe unterrichtet Business English im Umkreis Bocholt."
exclude: [Gemfile, Gemfile.lock, Rakefile, Rakefile.config, business-english.sublime-project, business-english.sublime-workspace]
url: https://arlol.github.io
baseurl: /business-english
language: de
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all
sass:
  style: compressed
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
