title:  "Business English in Bocholt"
description: "Mary O'Keeffe unterrichtet Business English im Umkreis Bocholt."
exclude: [Gemfile, Gemfile.lock, Rakefile, Rakefile.config, business-english.sublime-project, business-english.sublime-workspace]
url: http://arlos-mbp.local.
baseurl: /~ArloLOK/business-english/
language: de
